# Generated by Django 4.0.7 on 2022-12-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_fav_ad_favorites_fav_ad_fav_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='fav',
            constraint=models.UniqueConstraint(fields=('user', 'ad'), name='unique_together'),
        ),
    ]
