# Generated by Django 4.0.7 on 2022-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='message',
            field=models.CharField(default='', max_length=30),
        ),
    ]
