# Generated by Django 4.0.7 on 2022-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0002_guess_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='message',
            field=models.CharField(default='', max_length=80),
        ),
    ]
